apiVersion: v1
kind: PersistentVolume
metadata:
  name: ashu-pv
spec:
  capacity:
    storage: 2Gi 
  accessModes:
    - ReadWriteOnce 
  hostPath: # taking storage from Minion 
    path: "/common/ashudb1" # on the minion this location will be created
    type: DirectoryOrCreate  # if not present
  