apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ashu-webapp
  name: ashu-webapp # name of deployment 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ashu-webapp
  strategy: {}
  template: # template section for pod --
    metadata:
      creationTimestamp: null
      labels:
        app: ashu-webapp
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress
        ports:
        - containerPort: 80
        env: # use 
        - name: WORDPRESS_DB_HOST # for DB URL 
          value: ashudb # name of service 
        - name: WORDPRESS_DB_PASSWORD # db password 
          valueFrom:
           secretKeyRef: # reading db password from Secret 
            name: ashudbsec # name of secret 
            key: mycred # key 
        resources: {}
status: {}
