apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: ashuk8s1
spec: {}
status: {}

---

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod1
  name: pod1
  namespace: ashuk8s1
spec:
  containers:
  - command:
    - sleep
    - "10000"
    image: ubuntu
    name: pod1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ashuvc1
  name: ashuvc1
  namespace: ashuk8s1
spec:
  ports:
  - name: "1234"
    port: 1234
    protocol: TCP
    targetPort: 1234
    nodePort: 30233
  selector:
    app: ashuvc1
  type: NodePort
status:
  loadBalancer: {}
