apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJwaHgub2Npci5pbyI6eyJ1c2VybmFtZSI6ImF4bWJ0ZzhqdWRrbC9sZWFybnRlY2hieW1lQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiTjAucnNdOTh7M09YVHVMUTB1RFEiLCJhdXRoIjoiWVhodFluUm5PR3AxWkd0c0wyeGxZWEp1ZEdWamFHSjViV1ZBWjIxaGFXd3VZMjl0T2s0d0xuSnpYVGs0ZXpOUFdGUjFURkV3ZFVSUiJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: ashusec
type: kubernetes.io/dockerconfigjson
